---
title: "Calculate metabolic enzyme activity step by step"
output:
  word_document: default
  html_document: default
date: '2023-11-02'
---
00 load data ----------------------------------
```{r setup, include=FALSE}
# 00 load data ----------------------------------
data(MetNetwork)
data(metabolites)
data(MetabolicEnzymes)
```
01 Identify metabolism-related genes ----------------------------------
```{r}
# 01 Identify metabolism-related genes ----------------------------------
MetGenes<- getMetGenes(network = MetNetwork,
                       metabolites = metabolites,
                       filter.pct=0.2,
                       gamma = 0.6,
                       tmax = 1000,
                       eps = 1e-10,
                       norm = TRUE)
```
02 Prepare input file for ARACNe-AP ----------------------------------
```{r}
# 02 Prepare input file for ARACNe-AP ----------------------------------
expression <- read.csv('./ExpressionMatrix.csv',row.names = 1)
expression <- as.matrix(expression)
expression_filtered <- expression[rownames(expression)%in%MetGenes,]

write.table(x = data.frame(regulon=MetabolicEnzymes),
            './path to ARACNe/regulon.txt',
            row.names = F,
            col.names = F)
write.table(x = expression_filtered,
            './path to ARACNe/Exp_matrix.txt',
            row.names = T,
            col.names = T)
# Run ARACNe-AP to construct GRNs


```
03 Calculate enzyme activity ----------------------------------
```{r}
# 03 Calculate enzyme activity ----------------------------------
regulon <- CreatMetRegulon('ARACNeOutputFile.txt',
                          expression_filtered)

EnzymeActivity <- CalEnzymeAct(expression_filtered,
                               regulon)
```
