
#' readAracne
#' read ARACNe-AP results
#' @param afile Character string indicating the name of the ARACNe network file
#' @param format Character string, indicating the format of the aracne file, either adj for adjacency matrixes generated by aracne, or 3col when the interactome is represented by a 3 columns text file, with regulator in the first column, target in the second and mutual information in the third column
#'
#' @return Regulon object
#' @export
#'
#' @examples
#' data(testExp)
#' regulon <- readAracne('re_network.txt')
readAracne <- function(afile,format = c("3col",
                                        "adj")){
  switch(format, adj = {
    aracne <- readAracneAdj(afile)
  }, `3col` = {
    tmp <- t(sapply(strsplit(readLines(afile), "\t"),
                    function(x) x[1:3]))
    aracne <- data.frame(tf = tmp[, 1], target = tmp[, 2],
                         mi = as.numeric(tmp[, 3])/max(as.numeric(tmp[, 3])))
  })
  aracne
}

#' CreatMetRegulon
#' Create regulon object based on ARACNe-AP results
#' @param afile Character string indicating the name of the ARACNe network file
#' @param eset a gene expression matrix with genes (probes) in rows and samples in columns
#'
#' @return Regulon object
#' @export
#'
#' @examples
#' data(testExp)
#' data(network)
#' regulon <- CreatMetRegulon(network, as.matrix(testExp))
CreatMetRegulon <- function(afile,eset){
  net_sel <- afile[,-4]
  write.table(net_sel,"./sel_network.txt",row.names = F,col.names = F,quote = F,sep = "\t")
  netdir <- "./sel_network.txt"
  regulon <- viper::aracne2regulon(afile=netdir,
                                   eset = eset,
                                   format = "3col")
  regulon
}

#' CalEnzymeAct
#' Calculation of metabolic enzyme activities using regulatory networks
#' @param regulon Regulon object
#' @param eset a gene expression matrix with genes (probes) in rows and samples in columns
#' @param ... Parameters passed to viper
#'
#' @return A matrix of inferred enzyme activity for each regulator gene in the network across all samples
#' @export
#'
#' @examples
#' data(testExp)
#' data(network)
#' regulon <- CreatMetRegulon(network, as.matrix(testExp))
#' enzyme_activity <- CalEnzymeAct(regulon,as.matrix(testExp))
CalEnzymeAct <- function(regulon,eset,...){
  viper::viper(eset,regulon,...)
}
