
#' readAracne
#' read ARACNe-AP results
#' @param afile Character string indicating the name of the ARACNe network file
#' @param format Character string, indicating the format of the aracne file, either adj for adjacency matrixes generated by aracne, or 3col when the interactome is represented by a 3 columns text file, with regulator in the first column, target in the second and mutual information in the third column
#'
#' @return Regulon object
#' @export
#'
#' @examples
#' regulon <- CreatMetFegulon('ARACNeOutputFile.txt',
# expression_filtered)
readAracne <- function(afile,format = c("3col",
                                        "adj")){
  switch(format, adj = {
    aracne <- readAracneAdj(afile)
  }, `3col` = {
    tmp <- t(sapply(strsplit(readLines(afile), "\t"),
                    function(x) x[1:3]))
    aracne <- data.frame(tf = tmp[, 1], target = tmp[, 2],
                         mi = as.numeric(tmp[, 3])/max(as.numeric(tmp[, 3])))
  })
  aracne
}

#' CreatMetRegulon
#' Create regulon object based on ARACNe-AP results
#' @param afile Character string indicating the name of the ARACNe network file
#' @param eset a gene expression matrix with genes (probes) in rows and samples in columns
#'
#' @return Regulon object
#' @export
#'
#' @examples
CreatMetRegulon <- function(afile,eset){
  regulon <- viper::aracne2regulon(afile=afile,
                            eset = eset,
                            format = "3col")
  regulon
}

#' CalEnzymeAct
#' Calculation of metabolic enzyme activities using regulatory networks
#' @param regulon Regulon object
#' @param eset a gene expression matrix with genes (probes) in rows and samples in columns
#' @param ... Parameters passed to viper
#'
#' @return A matrix of inferred enzyme activity for each regulator gene in the network across all samples
#' @export
#'
#' @examples
CalEnzymeAct <- function(regulon,eset,...){
  viper::viper(eset,regulon,...)
}
